// Token usage
export interface TokenUsage {
  prompt_tokens: number
  completion_tokens: number
  total_tokens: number
}

// ReAct events
export interface ReactStepEvent {
  /** Step kind. V3: "thinking"/"iteration"/"answer". Legacy: "tool_start"/"tool_call"/"start"/"done". */
  type: "thinking" | "iteration" | "answer" | "start" | "done" | "tool_start" | "tool_call" | "final_answer"
  /** Lifecycle status (V3). Legacy events omit this; normalized by the hook. */
  status?: "start" | "done"
  iteration?: number
  tool_name?: string
  tool_args?: Record<string, unknown>
  reasoning?: string
  observation?: string
  error?: string
  /** Server-side iteration elapsed (LLM thinking + tool execution). */
  iter_elapsed?: number
  content_type?: string
  artifacts?: Array<{
    name: string
    url: string
    mime_type: string
    size: number
  }>
}

export interface ReactDoneEvent {
  answer: string
  iterations: number
  elapsed: number
  /** Server-side elapsed for the final iteration (LLM thinking → answer). */
  iter_elapsed?: number
  /** Token usage for the entire agent run. */
  usage?: TokenUsage
  /** Suggested follow-up questions generated by the agent. */
  suggestions?: string[]
  /** Auto-generated conversation title (first message only). */
  title?: string
}

// DAG events
export interface DagPhaseEvent {
  name: "planning" | "executing" | "analyzing" | "replanning"
  status: "start" | "done"
  round?: number
  steps?: Array<{
    id: string
    task: string
    deps: string[]
    tool_hint?: string
  }>
  results?: Array<{
    id: string
    task: string
    status: string
    result?: string
    started_at?: number
    completed_at?: number
    duration?: number
  }>
  achieved?: boolean
  confidence?: number
  reasoning?: string
}

export interface DagStepProgressEvent {
  step_id: string
  event: "started" | "iteration" | "completed"
  task?: string
  status?: string
  result?: string
  duration?: number
  started_at?: number
  // iteration fields
  type?: string
  iteration?: number
  tool_name?: string
  tool_args?: Record<string, unknown>
  reasoning?: string
  observation?: string
  error?: string
  /** Server-side iteration elapsed (available on iteration completion). */
  iter_elapsed?: number
  /** Per-step token usage (available on "completed" events). */
  usage?: TokenUsage
  content_type?: string
  artifacts?: Array<{
    name: string
    url: string
    mime_type: string
    size: number
  }>
}

export interface DagDoneEvent {
  answer: string
  achieved: boolean
  confidence: number
  elapsed: number
  /** Total number of plan-execute-analyze rounds (>1 means re-planning occurred). */
  rounds?: number
  /** Aggregated token usage across all DAG phases. */
  usage?: TokenUsage
  /** Suggested follow-up questions generated by the agent. */
  suggestions?: string[]
  /** Auto-generated conversation title (first message only). */
  title?: string
}
