"""Post-execution citation verification for high-accuracy domains.

Extracts legal, medical, and financial citations from step results and
verifies them via LLM judgment.  Designed to catch hallucinated article
numbers, fabricated case references, and incorrect regulatory citations
that pass the generic step verifier.
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field
from typing import Any

from fim_one.core.model.base import BaseLLM
from fim_one.core.model.structured import structured_llm_call
from fim_one.core.model.types import ChatMessage

logger = logging.getLogger(__name__)

# Max chars of step result sent to the verification prompt.
_CITATION_VERIFY_TRUNCATION = int(
    os.getenv("DAG_CITATION_VERIFY_TRUNCATION", "6000")
)

# ---------------------------------------------------------------------------
# Citation extraction patterns
# ---------------------------------------------------------------------------

# Chinese law citations: 《商标法》第五十七条, 《反不正当竞争法》第6条第2款
_CN_LAW_PATTERN = re.compile(
    r"《[^》]{2,30}》"
    r"(?:第[零一二三四五六七八九十百千\d]+条"
    r"(?:第[零一二三四五六七八九十百千\d]+款)?)?",
)

# Chinese case references: （2025）京73民终xxx号
_CN_CASE_PATTERN = re.compile(
    r"[（(]\d{4}[）)][^）)\s]{2,20}号",
)

# US/intl law references: Section 43(a), Article 13, TDRA
_INTL_LAW_PATTERN = re.compile(
    r"(?:Section|Article|§)\s*\d+(?:\([a-z]\))?",
    re.IGNORECASE,
)

# Domain keywords that indicate high-accuracy requirements.
_DOMAIN_KEYWORDS = re.compile(
    r"法律|法规|法条|商标法|反不正当竞争|广告法|合同法|刑法|民法典|知识产权"
    r"|trademark|patent|copyright|statute|regulation|compliance|Lanham"
    r"|医疗|药品|临床|诊断|medical|pharmaceutical|clinical"
    r"|金融|证券|税务|审计|financial|securities|accounting|tax",
    re.IGNORECASE,
)


@dataclass
class CitationVerifyResult:
    """Outcome of citation verification.

    Attributes:
        passed: Whether all citations appear accurate.
        citations_found: Number of citations extracted.
        issues: List of flagged inaccuracies.
        suggestions: LLM-generated correction suggestions.
    """

    passed: bool
    citations_found: int = 0
    issues: list[str] = field(default_factory=list)
    suggestions: str = ""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def should_verify_citations(task: str, result: str) -> bool:
    """Heuristic check: does this step's content warrant citation verification?

    Returns ``True`` when the task description or result text contains
    domain-specific keywords indicating legal, medical, or financial content.
    """
    combined = (task + " " + result)[:4000]
    return bool(_DOMAIN_KEYWORDS.search(combined))


def extract_citations(text: str) -> list[str]:
    """Extract all recognisable citations from *text*."""
    citations: list[str] = []
    for pattern in (_CN_LAW_PATTERN, _CN_CASE_PATTERN, _INTL_LAW_PATTERN):
        citations.extend(pattern.findall(text))
    # Deduplicate while preserving order.
    seen: set[str] = set()
    unique: list[str] = []
    for c in citations:
        if c not in seen:
            seen.add(c)
            unique.append(c)
    return unique


_VERIFICATION_PROMPT = """\
You are a citation-accuracy auditor.  A report was generated by an AI agent.  \
Your job is to check whether the legal, regulatory, or case citations in the \
report are ACCURATE.

## Extracted citations
{citations}

## Report excerpt (truncated)
{result}

For each citation, judge:
1. Does the cited article/section number match the actual content described?
   (e.g. if the report says "《反不正当竞争法》第5条 禁止擅自使用他人商品名称", \
but Article 5 is actually about government supervision duties, flag it.)
2. For case references, does the case name / year / court / outcome seem \
plausible, or does it look fabricated?

Respond with JSON:
{{
  "passed": true/false,
  "issues": ["issue 1", "issue 2", ...],
  "suggestions": "brief correction guidance"
}}

Set "passed" to true ONLY if all citations appear accurate.  If you are \
uncertain about a citation, flag it as an issue rather than letting it pass.
"""

_VERIFICATION_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "passed": {"type": "boolean"},
        "issues": {
            "type": "array",
            "items": {"type": "string"},
        },
        "suggestions": {"type": "string"},
    },
    "required": ["passed", "issues"],
}


async def verify_citations(
    result_text: str,
    llm: BaseLLM,
) -> CitationVerifyResult:
    """Verify citations in *result_text* using LLM judgment.

    Args:
        result_text: The step result to verify.
        llm: The LLM to use for verification (should be a capable model).

    Returns:
        A :class:`CitationVerifyResult` with the verdict.
    """
    citations = extract_citations(result_text)
    if not citations:
        return CitationVerifyResult(passed=True, citations_found=0)

    truncated = result_text[:_CITATION_VERIFY_TRUNCATION]
    citation_block = "\n".join(f"- {c}" for c in citations[:30])

    prompt = _VERIFICATION_PROMPT.format(
        citations=citation_block,
        result=truncated,
    )

    messages = [ChatMessage(role="user", content=prompt)]

    try:
        call_result = await structured_llm_call(
            llm,
            messages,
            schema=_VERIFICATION_SCHEMA,
            function_name="verify_citations",
            default_value={"passed": True, "issues": [], "suggestions": ""},
            temperature=0.0,
        )
        data = call_result.value
        issues = data.get("issues", []) if isinstance(data, dict) else []
        return CitationVerifyResult(
            passed=bool(data.get("passed", True)) if isinstance(data, dict) else True,
            citations_found=len(citations),
            issues=[str(i) for i in issues] if isinstance(issues, list) else [],
            suggestions=str(data.get("suggestions", "")) if isinstance(data, dict) else "",
        )
    except Exception as exc:
        logger.warning("Citation verification failed, defaulting to passed: %s", exc)
        return CitationVerifyResult(
            passed=True,
            citations_found=len(citations),
            suggestions=f"Verification error: {exc}",
        )
